compilecode: Fix handling of '-' inside groups
pfalcon/re1.5 pull request #30
Opened 2017-07-31 14:54 UTC by deshipu

Fix https://github.com/micropython/micropython/issues/3178

When '-' appears at the end of a class, treat it as literal '-'.

Copied from https://github.com/micropython/micropython/pull/3239

2017-08-01 14:30 UTC, pfalcon requested changes
My concern is that this adds extra code without adding new functionality. For example, it was possible to have literal "-" in the char class, it just needs to be first. This change perhaps good for MicroPython, but I'm not sure it's good for re1.5. I'd suggest wrapping this change in some #ifdef like "EXTRA_SYNTAX or something.

2017-08-01 14:30 UTC, pfalcon commented on compilecode.c
> +                        re += 1;
Please use native C increment, like surrounding code.

2017-08-01 14:30 UTC, pfalcon commented on compilecode.c
> +                    if (re[2] == ']') {
Please add a comment what this "if" clause handles.

2017-08-02 08:55 UTC, pfalcon commented on compilecode.c
> +            int sub = 0;
This should not be a part of this or another patch.

2017-09-24 07:18 UTC, pfalcon commented
Fixed with minimum extra code in https://github.com/pfalcon/re1.5/commit/bbfe74ae353615dbc3d7f6d54b4d315530fe06fb and testcases in https://github.com/pfalcon/re1.5/commit/53ec8fbfbf81819340433ce26b6f2697376f5c64

2017-09-24 07:18 UTC, closed without merging

2017-09-24 09:27 UTC, deshipu commented
I'm confused. First you say that this change is not welcome in this project, and then you make it yourself.